version: "2"
services:
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    volumes:
      - ./internal:/go/src/ctco-dev/go-api-template/internal
      - ./cmd:/go/src/ctco-dev/go-api-template/cmd    
    depends_on:
     - mongo
    ports:
      - 3000:3000
    environment:
      - JOKE_SERVICE_URL
      - USERS_ENABLED
      - USERS_MONGODB_DATABASE
      - USERS_MONGODB_COLLECTION_USERS
      - USERS_ROUTE
      - USERS_MONGODB_HOST=mongodb://mongo:27017
    tty: true
  mongo:
    image: mongo
    volumes:
      - /data/db