version: "2"
services:
  app:
    build:
      context: .
      dockerfile: build/Dockerfile
    ports:
      - 3000:3000
    environment:
      - JOKE_SERVICE_URL
      - USERS_ENABLED
      - USERS_MONGODB_DATABASE
      - USERS_MONGODB_COLLECTION_USERS
      - USERS_ROUTE
      - USERS_MONGODB_HOST
    tty: true